# Generated by Django 6.0.5 on 2026-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=255)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('option_a_text', models.CharField(blank=True, max_length=100)),
                ('option_a_image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('option_b_text', models.CharField(blank=True, max_length=100)),
                ('option_b_image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('option_c_text', models.CharField(blank=True, max_length=100)),
                ('option_c_image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('option_d_text', models.CharField(blank=True, max_length=100)),
                ('option_d_image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
    ]
