# Generated by Django 6.0.5 on 2026-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', '易'), ('medium', '中'), ('hard', '難')], default='medium', max_length=10, verbose_name='難易度'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正確答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='A 選項圖片'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='A 選項文字'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='B 選項圖片'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='B 選項文字'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='C 選項圖片'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='C 選項文字'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='D 選項圖片'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='D 選項文字'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='題目圖片'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='題目文字'),
        ),
    ]
