# Generated by Django 6.0.5 on 2026-06-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_difficulty_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='使用者 Session')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='測驗題數')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='分數')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='答對題數')),
                ('started_at', models.DateTimeField(verbose_name='開始時間')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='作答秒數')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_number', models.PositiveIntegerField(verbose_name='題號')),
                ('option_order', models.CharField(max_length=20, verbose_name='選項原始順序')),
                ('user_answer', models.CharField(blank=True, max_length=1, verbose_name='使用者答案')),
                ('user_display_answer', models.CharField(blank=True, max_length=1, verbose_name='畫面顯示答案')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='正確答案')),
                ('correct_display_answer', models.CharField(max_length=1, verbose_name='畫面顯示正確答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否答對')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='題目')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='測驗紀錄')),
            ],
            options={
                'ordering': ['display_number'],
            },
        ),
    ]
