# Generated by Django 6.0.5 on 2026-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quizattempt_session_key_quizattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user_attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='使用者測驗編號'),
        ),
    ]
