# Generated by Django 6.0.5 on 2026-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizattempt_user_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='correct_answer_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='正確答案內容'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='user_answer_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='使用者答案內容'),
        ),
    ]
